name: Foodgram Tests

on:
  push:
    branches: [ main, develop, develop_2]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Pull selenoid image
      run: docker pull selenoid/chrome:128.0

    - name: Run tests in docker
      run: docker compose up --build --exit-code-from test